DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    state VARCHAR(20) NOT NULL
);

CREATE TABLE users (
    name VARCHAR(100) PRIMARY KEY,
    password VARCHAR(100)
);
