stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - go build
  tags:
    - docker

test-job:
  stage: test
  script:
    - go test ./...
  tags:
    - docker

lint-job:
  stage: test
  script:
    - apt-get update -qy && apt-get install -y curl
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.45.0
    - ~/bin/golangci-lint run
  tags:
    - docker
