name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  run_test:
    name: Run Test
    runs-on: ubuntu-22.04
    steps:
      - name: Pull the current repository
        uses: actions/checkout@v3

      - name: Run Unit tests
        run: go test ./...
